version: '3.5'
services:
  api:
    container_name: arrenda-api
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
    networks:
      - arrenda-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - arrenda-db

  arrenda-db:
    restart: always
    container_name: arrenda-db
    hostname: arrenda-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_USER=${DB_PASS}
      - ALLOW
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - arrenda-network
volumes:
  pgdata:
    driver: local
networks:
  arrenda-network:
    name: network
    driver: bridge
